"""initial schema

Revision ID: c4a9afe7a07f
Revises: 
Create Date: 2026-01-11 15:34:55.147502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4a9afe7a07f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language_primary', sa.String(), nullable=False),
    sa.Column('languages_available', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='programstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('program_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('variant', sa.Enum('portrait', 'landscape', 'square', 'banner', name='assetvariant'), nullable=False),
    sa.Column('asset_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_topics',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('program_id', 'topic_id')
    )
    op.create_table('terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('term_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('video', 'article', name='content_type'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('content_language_primary', sa.Text(), nullable=False),
    sa.Column('content_languages_available', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('content_urls_by_language', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtitle_languages', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('subtitle_urls_by_language', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', 'archived', name='lessonstatus'), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('variant', sa.Enum('portrait', 'landscape', 'square', 'banner', name='assetvariant'), nullable=False),
    sa.Column('asset_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_assets')
    op.drop_table('lessons')
    op.drop_table('terms')
    op.drop_table('program_topics')
    op.drop_table('program_assets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('topics')
    op.drop_table('programs')
    # ### end Alembic commands ###
